apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: poison-pill.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PoisonPillConfig is the Schema for the poisonpillconfigs API
      displayName: Poison Pill Config
      kind: PoisonPillConfig
      name: poisonpillconfigs.poison-pill.medik8s.io
      version: v1alpha1
    - description: PoisonPillRemediation is the Schema for the poisonpillremediations API
      displayName: Poison Pill Remediation
      kind: PoisonPillRemediation
      name: poisonpillremediations.poison-pill.medik8s.io
      version: v1alpha1
    - description: PoisonPillRemediationTemplate is the Schema for the poisonpillremediationtemplates API
      displayName: Poison Pill Remediation Template
      kind: PoisonPillRemediationTemplate
      name: poisonpillremediationtemplates.poison-pill.medik8s.io
      version: v1alpha1
  description: This poison pill operator is using an alternate mechanism for a node in a cluster to detect its health status and take actions to remediate itself in case of a failure. While not all remediation events can result in the node returning to a healthy state, the operator does allow surviving parts of the cluster to assume the node has reached a safe state so that it’s workloads can be automatically recovered
  displayName: Poison Pill Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - fencing
  - remediation
  - auto-healing
  - recovery
  - high-availability
  - baremetal
  links:
  - name: Poison Pill
    url: https://poison-pill.domain
  maturity: alpha
  provider:
    name: Medik8s
    url: https://www.medik8s.io/
  version: 0.0.0
